subject_dir={
'N1':'N1_Virgile',
'N2':'N2_Alissa',
'N3':'N3_Ariane',
'N4':'N4_Xavier',
'N5':'N5_Viviane',
'S1':'S1_Rondeau',
'S2':'S2_Green',
'S3':'S3_Ouattara',
'S4':'S4_Paquin',
'S5':'S5_Lapointe',
'S6':'S6_Fracoeur',
'S7':'S7_Suarez_Paez',
'S8':'S8_Beland',
'S9':'S9',
'XG':'X_Gauthier',
'XL':'X_Lanthier',
'PT':'poissant',
}

files_list={
'N1':{
    'a_ac':'BED CYCLING_active_assis.mat',
    'a_bl':'BED CYCLING_baseline_assis.mat',
    'a_05':'BED CYCLING_5min_assis.mat',
    'a_10':'BED CYCLING_10min_assis.mat',
    'a_15':'BED CYCLING_15min_assis.mat',
    'a_20':'BED CYCLING_20min_assis.mat',
    'a_25':'BED CYCLING_25min_assis.mat',

    'c_bl':'BED CYCLING_baseline_couché.mat',
    'c_05':'BED CYCLING_5 min_couché.mat',
    'c_10':'BED CYCLING_10 min_couché.mat',
    'c_15':'BED CYCLING_15 min_couché.mat',
    'c_20':'BED CYCLING_20 min_couché.mat',
    'c_25':'BED CYCLING_25min_couché.mat',
    },
'N2':{
    'a_bl':'BED CYCLING_baseline_assis.mat',
    'a_05':'BED CYCLING_5min_assise.mat',
    'a_10':'BED CYCLING_10min_assis.mat',
    'a_15':'BED CYCLING_15min_assis.mat',
    'a_20':'BED CYCLING_20min_assis.mat',
    'a_25':'BED CYCLING_25min_assis.mat',

    'c_bl':'BED CYCLING_baseline.mat',
    'c_05':'BED CYCLING_5min_couché.mat',
    'c_10':'BED CYCLING_10min_couché.mat',
    'c_15':'BED CYCLING_15min_couché.mat',
    'c_20':'BED CYCLING_20min_couché.mat',
    'c_25':'BED CYCLING_25min_couché.mat',
    'c_30':'BED CYCLING_30min_repos.mat',
    },
'N3':{
    'a_bl':'BED CYCLING_baseline_assis.mat',
    'a_05':'BED CYCLING_5min_assis.mat',
    'a_10':'BED CYCLING_10min_assis.mat',
    'a_15':'BED CYCLING_15min_assis.mat',
    'a_25':'BED CYCLING_25min_assis.mat',
    'a_bl2':'BED CYCLING_restpostvélo_assis.mat',

    'c_bl':'BED CYCLING_avant_baseline.mat',
    'c_05':'BED CYCLING_pendant_5min.mat',
    'c_10':'BED CYCLING_pendant_10min.mat',
    'c_15':'BED CYCLING_pendant_15min.mat',
    'c_20':'BED CYCLING_pendant_20.mat',
    'c_25':'BED CYCLING_pendant 25.mat',
    'c_bl2':'baseline_prévélo_couché.mat',
    },
'N4':{},
'N5':{
    'a_ac':'BED CYCLING_active_assis.mat',
    'a_bl':'BED CYCLING_baseline_assis.mat',
    'a_05':'BED CYCLING_5min_assis.mat',
    'a_10':'BED CYCLING_10min.mat',
    'a_15':'BED CYCLING_15min.mat',
    'a_20':'BED CYCLING_20min.mat',
    'a_25':'BED CYCLING_25min_assis.mat',
    'a_30':'BED CYCLING_30min_assis.mat',
    },
'S1':{
    'a_bl':'BED CYCLING_baseline_assis.mat',
    'a_05':'BED CYCLING_assis_5min.mat',

    'c_bl':'BED CYCLING_base3line_couché.mat',
    'c_01':'BED CYCLING_1min_couché.mat',
    'c_05':'BED CYCLING_couché_5min.mat',
    'c_10':'BED CYCLING_10min_couché.mat',
    'c_15':'BED CYCLING_15min_couché.mat',
    'c_20':'BED CYCLING_20min_couché.mat',
    'c_25':'BED CYCLING_25min_couché.mat',
    'c_30':'BED CYCLING_30min_couché.mat',
    },
'S2':{
    'a_bl':'BED CYCLING_baseline_assis.mat',
    'a_05':'BED CYCLING_5min_assis.mat',
    'a_10':'BED CYCLING_10min_assis.mat',

    'c_bl':'BED CYCLING_baseline_couché.mat',
    'c_05':'BED CYCLING_5min_couché.mat',
    'c_10':'BED CYCLING_10min_couché.mat',
    'c_15':'BED CYCLING_15min_couché(actif).mat',
    },
'S3':{
    'a_bl':'BED CYCLING_assis_baseline.mat',
    'a_01':'BED CYCLING_1min_assis.mat',
    'a_05':'BED CYCLING_assis_5min.mat',
    'a_14':'BED CYCLING_active_14min_assis.mat',
    'a_15':'BED CYCLING_assis_15min.mat',
    'a_20':'BED CYCLING_20min_assis.mat',
    'a_25':'BED CYCLING_25min_assis.mat',
    'a_28':'BED CYCLING_active_28min.mat',
    'a_29':'BED CYCLING_assis_29min.mat',

    'c_bl':'BED CYCLING_baseline_couché.mat',
    'c_01':'BED CYCLING_couché_1min.mat',
    'c_05':'BED CYCLING_couché_semiactif_5min.mat',
    'c_10':'BED CYCLING_10min_couché.mat',
    'c_10_1':'BED CYCLING_10min_couché-1.mat',
    'c_15':'BED CYCLING_couché_15min.mat',
    'c_18':'BED CYCLING_couché_actif_18min.mat',
    'c_20':'BED CYCLING_couché_20min.mat',
    'c_25':'BED CYCLING_25min_couché.mat',
    },
'S4':{
    'a_bl':'BED CYCLING_baseline_assis.mat',
    'a_01':'BED CYCLING_1min_assis.mat',
    'a_05':'BED CYCLING_5min_assis.mat',
    'a_10':'BED CYCLING_10min_assis.mat',
    'a_10_1':'BED CYCLING_10min_assis-1.mat',
    'a_15':'BED CYCLING_15min_assis.mat',
    'a_18':'BED CYCLING_active_18min_assis.mat',
    'a_20':'BED CYCLING_20min_assis.mat',
    'a_25':'BED CYCLING_25min_assis.mat',
    'a_29':'BED CYCLING_29min_assis.mat',

    'c_bl':'BED CYCLING_baseline_couché.mat',
    'c_05':'BED CYCLING_5min_couché.mat',
    'c_15':'BED CYCLING_15min_couché.mat',
    'c_20':'BED CYCLING_20min_couché.mat',
    'c_25':'BED CYCLING_25min_couché.mat',
    'c_29':'BED CYCLING_29min_active_couché.mat',
    },
'S5':{
    'a_bl':'BED CYCLING_BASELINE_ASSIS.mat',
    'a_01':'BED CYCLING_1min_assis.mat',
    'a_05':'BED CYCLING_5min_assis.mat',
    'a_10':'BED CYCLING_10min_assis.mat',
    'a_15':'BED CYCLING_assis_15min.mat',
    'a_20':'BED CYCLING_20min_assis.mat',

    'c_bl':'BED CYCLING_baseline_couché.mat',
    'c_01':'BED CYCLING_1min_couché.mat',
    'c_05':'BED CYCLING_5min_couché.mat',
    'c_10':'BED CYCLING_10min_couché.mat',
    'c_15':'BED CYCLING_15min_couché.mat',
    'c_20':'BED CYCLING_couché_20min.mat',
    },
'S6':{
    'a_bl':'BED CYCLING_baseline_assis.mat',
    'a_07':'BED CYCLING_7min_assis.mat',
    'a_10':'BED CYCLING_10min_assis.mat',
    'a_15':'BED CYCLING_15min_assis.mat',
    'a_20':'BED CYCLING_20min_assis.mat',
    'a_25':'BED CYCLING_25min_assis.mat',
    'a_29':'BED CYCLING_assis_29min.mat',

    'c_bl':'BED CYCLING_baseline.mat',
    'c_02':'BED CYCLING_2min_couché.mat',
    'c_05':'BED CYCLING_5min_couché.mat',
    'c_10':'BED CYCLING_10min_couché.mat',
    'c_15':'BED CYCLING_15min_couché.mat',
    'c_20':'BED CYCLING_20min_couché.mat',
    'c_25':'BED CYCLING_25min_couché.mat',
    'c_29':'BED CYCLING_couché_29min.mat',
    },
'S7':{
    'a_bl':'BED CYCLING_baseline.mat',
    'a_05':'BED CYCLING_5min_assis.mat',
    'a_10':'BED CYCLING_10min_assis.mat',   
    'a_15':'BED CYCLING_15min_assis.mat',   
    'a_20':'BED CYCLING_20min_assis.mat',    
    'a_25':'BED CYCLING_25min_assis.mat',    
    'a_29':'BED CYCLING_29min_assis.mat',    

    'c_bl':'BED CYCLING.mat',
    'c_05':'BED CYCLING_5min_couché.mat',
    'c_10':'BED CYCLING_10min_couché.mat',  
    'c_15':'BED CYCLING_15min_couché.mat',   
    'c_20':'BED CYCLING_20min_couché.mat',   
    'c_25':'BED CYCLING_25min_couché.mat',   
    'c_29':'BED CYCLING_29min_couché.mat',   
    },
'S8':{
    'a_bl':'BED CYCLING_assis_baseline.mat',
    'a_05':'BED CYCLING_assis_5min.mat',
    'a_10':'BED CYCLING_assis_10min.mat',
    'a_15':'BED CYCLING_15min_assis.mat',
    'a_20':'BED CYCLING_20min_assis.mat',
    'a_25':'BED CYCLING_25min_assis.mat',
    'a_29':'BED CYCLING_29min_assis.mat',

    'c_bl':'BED CYCLING_baseline_couché.mat',
    'c_05':'BED CYCLING_couché_5min.mat',
    'c_10':'BED CYCLING_10min_couché.mat',
    'c_15':'BED CYCLING_15min_couché.mat',
    'c_20':'BED CYCLING_20min_couché.mat',
    'c_25':'BED CYCLING_25min_couché.mat',
    'c_29':'BED CYCLING_29min_couché.mat',
    },
'S9':{
    'a_bl':'BED CYCLING_assis_baseline.mat',
    'a_01':'BED CYCLING_assis_1min.mat',
    'a_05':'BED CYCLING_5min_assis.mat',
    'a_10':'BED CYCLING_assis_10min.mat',
    'a_15':'BED CYCLING_15min_assis.mat',
    'a_20':'BED CYCLING_20min_assis.mat',
    'a_25':'BED CYCLING_25min_assis.mat',
    'a_29a':'BED CYCLING_29min_assis_actif.mat',
    },
'XG':{
    'a_bl':'BED CYCLING.mat',
    'a_05':'BED CYCLING_5min_assis.mat',
    'a_10':'BED CYCLING_10-15min.mat',
    'a_20':'BED CYCLING_20-25min_assis.mat',
    'a_30':'BED CYCLING_post30min_assis.mat',
    },
'XL':{
    'a_bl':'BED CYCLING_baseline_assis.mat',
    'a_05':'BED CYCLING_5min_assis.mat',
    'a_10':'BED CYCLING_10min_assis.mat',
    'a_15':'BED CYCLING_15min_assis.mat',
    'a_20':'BED CYCLING_20min_assis.mat',
    'a_25':'BED CYCLING_25min_assis.mat',
    'a_30':'BED CYCLING_30min_assis.mat',
    },
'PT':{
    'a_bl':'BED CYCLING_baseline_assis.mat',
    'a_05':'BED CYCLING_5min_assis.mat',
    'a_10':'BED CYCLING_10min_assis.mat',
    'a_15':'BED CYCLING_15min_assis.mat',
    'a_20':'BED CYCLING_20min_assis.mat',
    'a_25':'BED CYCLING_assis_25min.mat',
    'a_29':'BED CYCLING_assis_29min.mat',

    'c_bl':'BED CYCLING_couché_baseline.mat',
    'c_02':'BED CYCLING_couché_2min.mat',
    'c_05':'BED CYCLING_5min_couché.mat',
    'c_10':'BED CYCLING_couché_10min.mat',
    'c_15':'BED CYCLING_couché_15min.mat',
    'c_20a':'BED CYCLING_20min_acitf_couché.mat',
    'c_25':'BED CYCLING_couché_25min.mat',
    },
}

files_channels = {
    'S2':{
        'a_bl':[1,9],
        'a_05':[1,9],
        'a_10':[1,9],

        'c_bl':[9,14],
        'c_05':[9,14],
        'c_10':[9,14],
        'c_15':[9,14],
        },
    'S3':{
        'a_bl':[9,16],
        'a_05':[9,16],
        'a_15':[9,16],
        'a_25':[9,16],

        'c_bl':[9,16],
        'c_05':[9,16],
        'c_15':[9,16],
        'c_25':[9,16],
        },
    'S4':{
        'a_bl':[9,16],
        'a_05':[9,16],
        'a_15':[9,16],
        'a_25':[1,8],

        'c_bl':[1,9],
        'c_05':[1,9],
        'c_15':[1,9],
        'c_25':[1,9],
        },
    'S9':{
        'a_bl':[1,9],
        'a_05':[1,9],
        'a_15':[1,9],
        'a_25':[1,9],
    },


}

signals_order = {
    'S2':{
        'a_bl':[3,1,7,5,2,0,6,4],
        'a_05':[3,1,7,5,2,0,6,4],
        'a_10':[3,1,7,5,2,0,6,4],

        'c_bl':[3,1,5,2,0,4],
        'c_05':[3,1,5,2,0,4],
        'c_10':[3,1,5,2,0,4],
        'c_15':[3,1,5,2,0,4],
        },
    'S3':{
        'a_bl':[3,1,7,5,2,0,6,4],
        'a_05':[3,1,7,5,2,0,6,4],
        'a_15':[3,1,7,5,2,0,6,4],
        'a_25':[3,1,7,5,2,0,6,4],

        'c_bl':[3,1,7,5,2,0,6,4],
        'c_05':[3,1,7,5,2,0,6,4],
        'c_15':[3,1,7,5,2,0,6,4],
        'c_25':[3,1,7,5,2,0,6,4],
        },
    'S4':{
        'a_bl':[3,1,7,5,2,0,6,4],
        'a_05':[3,1,7,5,2,0,6,4],
        'a_15':[3,1,7,5,2,0,6,4],
        'a_25':[3,1,7,5,2,0,6,],

        'c_bl':[3,1,7,5,2,0,6,4],
        'c_05':[3,1,7,5,2,0,6,4],
        'c_15':[3,1,7,5,2,0,6,4],
        'c_25':[3,1,7,5,2,0,6,4],
        },
    'S9':{
        'a_bl':[3,1,7,5,2,0,6,4],
        'a_05':[3,1,7,5,2,0,6,4],
        'a_15':[3,1,7,5,2,0,6,4],
        'a_25':[3,1,7,5,2,0,6,4],
    },

}

signals_title = {
    'S2':{
        'a_bl':'S2: ABT sitting baseline',
        'a_05':'S2: ABT sitting 05 min',
        'a_10':'S2: ABT sitting 10 min',

        'c_bl':'S2: ABT lying baseline',
        'c_05':'S2: ABT lying 05 min',
        'c_10':'S2: ABT lying 10 min', 
        'c_15':'S2: ABT lying 15 min',
        },
    'S3':{ 
        'a_bl':'S3: ABT sitting baseline',
        'a_05':'S3: ABT sitting 05 min',
        'a_15':'S3: ABT sitting 15 min',
        'a_25':'S3: ABT sitting 25 min',

        'c_bl':'S3: ABT lying baseline',
        'c_05':'S3: ABT lying 05 min',
        'c_15':'S3: ABT lying 15 min', 
        'c_25':'S3: ABT lying 25 min',
        },
    'S4':{ 
        'a_bl':'S4: ABT sitting baseline',
        'a_05':'S4: ABT sitting 05 min',
        'a_15':'S4: ABT sitting 15 min',
        'a_25':'S4: ABT sitting 25 min',

        'c_bl':'S4: ABT lying baseline',
        'c_05':'S4: ABT lying 05 min',
        'c_15':'S4: ABT lying 15 min', 
        'c_25':'S4: ABT lying 25 min',
        },
    'S9':{ 
        'a_bl':'S9: ABT sitting baseline',
        'a_05':'S9: ABT sitting 05 min',
        'a_15':'S9: ABT sitting 15 min',
        'a_25':'S9: ABT sitting 25 min',
    },

}

filenames_figures = {
    'S2':{
        'a_bl':'S2_sitting_bl.png',
        'a_05':'S2_sitting_05.png',
        'a_10':'S2_sitting_10.png',

        'c_bl':'S2_lying_bl.png',
        'c_05':'S2_lying_05.png',
        'c_10':'S2_lying_10.png',
        'c_15':'S2_lying_15.png',
    },
    'S3':{
        'a_bl':'S3_sitting_bl.png',
        'a_05':'S3_sitting_05.png',
        'a_15':'S3_sitting_15.png',
        'a_25':'S3_sitting_25.png',

        'c_bl':'S3_lying_bl.png',
        'c_05':'S3_lying_05.png',
        'c_15':'S3_lying_15.png',
        'c_25':'S3_lying_25.png',
    },
    'S4':{
        'a_bl':'S4_sitting_bl.png',
        'a_05':'S4_sitting_05.png',
        'a_15':'S4_sitting_15.png',
        'a_25':'S4_sitting_25.png',

        'c_bl':'S4_lying_bl.png',
        'c_05':'S4_lying_05.png',
        'c_15':'S4_lying_15.png',
        'c_25':'S4_lying_25.png',
    },
    'S9':{
        'a_bl':'S9_sitting_bl.png',
        'a_05':'S9_sitting_05.png',
        'a_15':'S9_sitting_15.png',
        'a_25':'S9_sitting_25.png',
    },
}



