from class_emg_ebc import Processing_EMG
import numpy as np
import pandas as pd
import scipy.io
import matplotlib.pyplot as plt


def main(args):
    
    session = int(args[1]) ## [1,7,14]
    num_file = int(args[2]) ## [0,1,2,3,4]-> (baseline_start, e1,e2,e2, baseline_end)
    
    if  session == 1:
        path='../data/emg_noraxon/matlab/s01/'
        files=['EBC040S1-Baseline1.mat','EBC040S1e1.mat','EBC040S1e2.mat','EBC040S1e3.mat', 'EBC040S1-Baseline2.mat']
    elif session == 7:
        path='../data/emg_noraxon/matlab/s07/'
        files=['EBC040_S7_BASELINE1.mat','EBC040_S7_E1.mat','EBC040_S7_E2.mat','EBC040_S7_E3.mat','EBC040_S7_BASELINE.mat']
    elif session == 14:
        path='../data/emg_noraxon/matlab/s14/'
        files=['EBC_Bed_cycling_Baseline.mat','EBC_Bed_cycling-s14-Baseline.mat','EBC040_Bed_cycling-S14.mat','EBC040_Bed_cycling-s14-5min.mat','EBC040-_Bed_cycling_-s14-15m.mat','EBC040_Bed_cycling-s14-30min.mat']
    else:
        print(f'The {session} session was not found.')
        return 0
    
    ## EMG early bed cycling (EBC) from .mat file (matlab file) generated by Noraxon software.
    ## Each file has several channels.
    ## We read the data in the class 'Processing_EMG'.
    ## We create an object (obj_emg) for a selected file, namely the num_file using de command:
    ## python emg_ebc.py 0 (for the first file:'EBC040S1-Baseline1.mat' ),
    ## python emg_ebc.py 1 (for the second file:'EBC040S1e1.mat'), etc.
    
    obj_emg = Processing_EMG(path,files[num_file])
    
    obj_emg.plotEMG()
    # obj_emg.plotPowerSpectrum()   
    
    ## Window size in mili-seconds (ms).
    ## Recommended values for window_size: between 50 and 100 ms.

    # ## Smoothing RMS 
    # window_size=50 # ms
    # obj_emg.smoothingRMS(window_size)
    # obj_emg.plotEMG_smoothed()

    plt.ion()
    plt.show(block=True)

    
    return 0

if __name__ == '__main__':
    import sys
    sys.exit(main(sys.argv))
