from class_emg_hreflex import Processing_EMG
import numpy as np
import pandas as pd
import scipy.io
import matplotlib.pyplot as plt


def main(args):
    # print('EMG processing')
    
    path='../data/h-ref_matlab_legacy/'
    files=['H-Reflexe.mat','H-Reflexe-1.mat']

    num_file = int(args[1])

    ## EMG h-reflex from .mat file (matlab file) generated by Noraxon software.
    ## We read the data in the class 'Processing_EMG'.
    ## We create an object (obj_emg) for a selected file, namely the num_file using de command:
    ## python emg_hreflex.py 0 (for the first file)
    ## python emg_hreflex.py 1 (for the second file)
    
    obj_emg = Processing_EMG(path,files[num_file])
    
    obj_emg.plotEMG()
    obj_emg.plotPowerSpectrum()
    

    plt.ion()
    plt.show(block=True)

    return 0

if __name__ == '__main__':
    import sys
    sys.exit(main(sys.argv))
